//Questão 03. Crie um programa em Javascript que leia uma temperatura em Fahrenheit e converta para Celsius, convertendo a formula a questão 02.Exiba o resultado em console.log.

let F = 61; // temperatura em Fahrenheit
let C = (F - 32) * 5/9; // converte para Celsius
window.alert(F + "°F equivalem a " + C + "°C"); //mostra a temperatura convertida
console.log(F + "°F equivalem a " + C + "°C"); //mostra a temperatura convertida no console